### ISSUE TITLE
Tap not working now

### ISSUE THREAD

**Issue by BrunIF** [Kyslik/homebrew-php#10]
## Description

Your tap (brew tap kyslik/homebrew-php) not working now.
Can You help me how to install php71-intl? 

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13.6_
**Homebrew version:**   | _Homebrew 1.7.1 / Homebrew/homebrew-core (git revision e5bab; last commit 2018-08-17)_
**PHP version in use:** | _7.1_

```bash
brew tap kyslik/homebrew-php
==> Tapping kyslik/php
Cloning into '/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php'...
remote: Counting objects: 785, done.
remote: Compressing objects: 100% (316/316), done.
remote: Total 785 (delta 527), reused 548 (delta 462), pack-reused 0
Receiving objects: 100% (785/785), 309.40 KiB | 221.00 KiB/s, done.
Resolving deltas: 100% (527/527), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php72-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php72-trader.rb:18:in `<class:Php72Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-trader.rb:18:in `<class:Php55Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-trader.rb:18:in `<class:Php54Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php53-mcrypt.rb                                                                                              [13/230]
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php53-mcrypt.rb:19:in `<class:Php53Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-trader.rb:18:in `<class:Php70Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-mcrypt.rb:19:in `<class:Php55Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php71-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php71-trader.rb:18:in `<class:Php71Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php56-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php56-trader.rb:18:in `<class:Php56Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-mcrypt.rb:19:in `<class:Php54Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap kyslik/php: invalid syntax in tap!
```

**Comment by Kyslik** [comment]
You have 10.13.6, so go to the homebrew-core repository and download php from there, that should work. Do not use this tap its only for my personal use and I do not maintain it unless someones make an PR. Good Luck! :)
